{% set version = "2.5" %}

package:
  name: pyseidon
  version: {{ version }}

source:
  url: https://github.com/GrumpyNounours/PySeidon/archive/v{{ version }}.tar.gz
  sha256: fc498611e01e3a832c080394df999585893db886ea494cfbee4c77e496fea267
  patches:
    # Workaround a `raw_input` [y/n] question.
    - setup.patch

build:
  number: 2
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python <3
    - pip
  run:
    - python <3
    - h5py
    - utide
    - numpy
    - pydap
    - scipy
    - pandas
    - seaborn
    - numexpr
    - netcdf4
    - networkx
    - matplotlib-base

test:
  imports:
    - pyseidon

about:
  home: https://github.com/GrumpyNounours/PySeidon
  license: GPL-3.0
  license_file: License_PySeidon.txt
  summary: Suite of tools for the tidal energy community and FVCOM users

extra:
  recipe-maintainers:
    - GrumpyNounours
    - ocefpaf
    - wesleybowman
