travis:
  secure:
    BINSTAR_TOKEN: mPrJ+CwMtFgN9vhEHf5mVm1Mhkx2KKNpWrUqN6EZ7pYyvU0n3CPFwL/hI7ICtn7wKhxlD8EdnlJE4xZ+FDCIAL7nzJJH1804uA9VNWzHv+gsKlm0CY6/B9f8TDfqBojer+E5FIrTwVlVxgxZPxKSQA0cPe3aoXecs3e7O3Q24t05gIBEx4z3xzG+5CX8fBGDYdgDBIssb3Gq/BBB5xrdLHVCIg34gvW0HCBkiy/ZOKSeY2Mds3rxtKJ5wsQPXE1cRA7+JlqCLllDo3HW4LWYktlM02/lk/2boF5Kxzq06AbXzJovYoT2IMotSVEedaltoFUPmWRzaP4BwAzOmw2V5TiKsf+0ZLdKam287kv4js9HFGYzSDzRXTbuJjLgTAauKrJP8dlX990lYqXbkisxZlrk24QYd2RUl9WoIJDFN6uz6JNk8CxwryNZE6ksh3ZwyvzIiMVTevaYdF1QtlcS+O7f0VZd10J5ZLq+SPeuWLq+V3mM4AEqvH0d36/uvK9Aldu6lZUIInYDt8HDq/kNTaRLyOjMVjwuNasqHNALnk8sMQh1uaNdLp0n6Sv7cyORyyfz1+1oion/8/UCNmZraFCaPhTtu6kOQNdbBmB2IRqMyxZ1ej7GfD/Qve4YH3jfen/o9oT3PcOOfSiv/bImmnHF1mhjvVg97QxCVwsDmrU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
